import type { Metadata } from 'next'
import { Inter, Prompt, Kanit } from 'next/font/google'
import './globals.css'
import NextWrapper from './NextWrapper'
import { Toaster } from 'react-hot-toast'

// const inter = Inter({ subsets: ['latin'] })
// const kanit = Kanit({ weight: "400", subsets: ["thai"]})
const prompt = Prompt({ weight: "400", subsets: ["thai"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <NextWrapper>
          <Toaster />
          {children}
        </NextWrapper>
      </body>
    </html>
  )
}
